# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenLie\ChatbotRasa\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'